# ワークフローの名前 (GitHubのActionsタブに表示されます)
name: Node.js CI

# ワークフローを実行する「きっかけ」（トリガー）
on:
  # mainブランチにプッシュされた時
  push:
    branches: [ main ]
  # mainブランチに対してプルリクエストが作成された時
  pull_request:
    branches: [ main ]

# 実行する「ジョブ」（作業内容）
jobs:
  # 'build' という名前のジョブ (名前は自由)
  build:
    # ジョブを実行する仮想環境 (Ubuntuの最新版)
    runs-on: ubuntu-latest

    # Node.jsのバージョンを指定 (プロジェクトに合わせて変更)
    strategy:
      matrix:
        node-version: [18.x, 20.x] # 2つのバージョンでテストする例

    # ジョブの「ステップ」（具体的な手順）
    steps:
      # 1. リポジトリのコードを仮想環境にコピーする (必須)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 指定したバージョンのNode.jsをセットアップする
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3. 依存パッケージをインストールする (npm ci は npm install より高速で確実)
      - name: Install dependencies
        run: npm ci

      # 4. ビルドが必要な場合 (なければこのステップは削除)
      # - name: Build project
      #   run: npm run build --if-present

      # 5. テストを実行する
      - name: Run tests
        run: npm test
