# ワークフローの名前
name: CI Checks (Example: HTML/CSS/JS Linting) # 名前を実態に合わせて変更

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint: # ジョブ名を変更 (例: lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- npm関連のステップは削除済み ---

      # 例: 将来的にLintを追加する場合のプレースホルダー
      # - name: Setup Node.js for Linting
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      # - name: Install ESLint (example)
      #   run: npm install eslint
      # - name: Run ESLint (example)
      #   run: npx eslint js/**/*.js
