# ワークフローの名前
name: CI Checks (JavaScript Linting) # 名前を実態に合わせて変更

# ワークフローを実行する「きっかけ」（トリガー）
on:
  workflow_dispatch: # 手動実行を可能にするトリガー
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint: # ジョブ名を lint に変更
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js環境をセットアップ (ESLintの実行に必要)
      - name: Setup Node.js for Linting
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # 使用するNode.jsのバージョンを指定

      # 3. ESLintをインストール
      - name: Install ESLint
        run: npm install eslint # ワークフロー内でESLintをインストール

      # 4. ESLintを実行 (jsフォルダ以下の全.jsファイルを対象)
      #    注意: リポジトリに eslint.config.js 等の設定ファイルが必要です
      - name: Run ESLint
        run: npx eslint js/**/*.js # jsフォルダ配下のJavaScriptファイルをチェック

